spring:
  # 相关的配置
  shardingsphere:
    props:
      sql-show: true
    datasource:
      # 配置数据源的名称
      names: master,slave1,slave2
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
      # 第一个数据源
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3316/db
        username: root
        password: 123456
      # 第二个数据源
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3326/db
        username: root
        password: 123456
      # 第三个数据源
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3336/db
        username: root
        password: 123456
    rules:
      replica-query:
        data-sources:
          ds:
            primary-data-source-name: master
            replica-data-source-names: slave1,slave2
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              defaule: 0
